### ISSUE TITLE
TO-DO

### ISSUE THREAD

**Issue by redlex-spb** [redlex-spb/go_pkg_sender#1]
- [x] Moving to gin-gonic
- [ ] Dynamic directory server
- [ ] Implement all the features of the "Remote Package Installer"
- [ ] Get upload speed
- [ ] Get remaining time
- [ ] Make GUI
